### ISSUE TITLE
Input images

### ISSUE THREAD

**Issue by Hassefar** [bartbutenaers/node-red-contrib-plate-recognizer#3]
Hi

First of all; what a great node!

I have purchased an EufyCam E2 which will not send video live (but only when trigged). The video can for example be sent via RTPS. However, how do I input an image in this case?

**Comment by bartbutenaers** [comment]
Hi,
Thanks!  There are dome discussions on the Node-RED forum (e.g. this [discussion](https://discourse.nodered.org/t/how-to-display-cctv-camera-in-dashboard-rtsp/5860/47?u=bartbutenaers)) about RTSP.  And if that doesn't work, you can ask your question there.  I'm going to to close this issue, since it is not related to this node.
Good luck with it 
Bart
